name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Go backend
      working-directory: ./backend
      run: go build -o ../backend/server

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Package Electron app
      working-directory: ./frontend
      run: npm run dist

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: ./frontend/dist

